name: Build Torro Pro APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          autoconf \
          automake \
          build-essential \
          ccache \
          cmake \
          gettext \
          git \
          libffi-dev \
          libltdl-dev \
          libssl-dev \
          libtool \
          openjdk-11-jdk \
          unzip \
          zip \
          zlib1g-dev \
          wget

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython==3.0.8

    - name: Setup Android SDK
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk
        cd ~/.buildozer/android/platform/android-sdk
        
        # Download command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools tools
        
        # Accept all Android licenses
        mkdir -p licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> licenses/android-sdk-license  
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > licenses/android-sdk-preview-license
        echo "601085b94cd77f0b54ff86406957099ebe79c4d6" > licenses/intel-android-extra-license
        
        # Install required packages
        yes | ./tools/bin/sdkmanager --sdk_root=$PWD "build-tools;33.0.0"
        yes | ./tools/bin/sdkmanager --sdk_root=$PWD "platforms;android-33"
        yes | ./tools/bin/sdkmanager --sdk_root=$PWD "platform-tools"
        yes | ./tools/bin/sdkmanager --sdk_root=$PWD "ndk;25.1.8937393"

    - name: Patch Python for Android to skip grp module
      run: |
        # Create a patch to disable grp module building
        cat > skip_grp.patch << 'EOF'
        --- a/pythonforandroid/recipes/python3/__init__.py
        +++ b/pythonforandroid/recipes/python3/__init__.py
        @@ -100,6 +100,9 @@ class Python3Recipe(Recipe):
                 'Modules/_ctypes/_ctypes.c',
                 'Modules/_ctypes/callbacks.c',
                 'Modules/_ctypes/callproc.c',])
        +        
        +        # Skip grp module
        +        self.configure_args.extend(['--disable-grp'])
             
             def get_recipe_env(self, arch=None, with_flags_in_cc=True):
                 env = super().get_recipe_env(arch, with_flags_in_cc)
        EOF
        
        # Apply the patch
        find ~/.local/lib/python*/site-packages/pythonforandroid/ -name "__init__.py" -path "*/recipes/python3/__init__.py" | head -1 | xargs -I {} cp {} {}.backup
        patch -p1 -d ~/.local/lib/python*/site-packages/pythonforandroid/recipes/python3/ < skip_grp.patch || true

    - name: Build APK with Buildozer
      run: |
        buildozer android clean
        buildozer -v android debug
      env:
        BUILDODER_CI: "1"
        BUILDODER_CMAKE: "1" 
        BUILDODER_CCACHE: "1"
        # Skip grp module explicitly
        PYTHON_DISABLE_MODULES: "grp"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: torro-pro-app
        path: bin/*.apk
        retention-days: 90

    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer
          bin
        retention-days: 30